/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.corneliu.forms.UI;

import javax.swing.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

/**
 *
 * @author corneliu
 */
public class ComputingDocumentTypePanel extends javax.swing.JPanel {


    private MainFrame2 mainFrame;

    /**
     * Creates new form ComputingDocumentTypePanel
     */
    public ComputingDocumentTypePanel(MainFrame2 mainFrame) {
        this.mainFrame = mainFrame;

        initComponents();

        computingDocTypeCombo.addActionListener(e -> this.mainFrame.reloadDictionary());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        computingDocTypeCombo = new javax.swing.JComboBox<>();

        computingDocTypeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Incendiu", "Securitate" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(computingDocTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(426, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(computingDocTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> computingDocTypeCombo;
    // End of variables declaration//GEN-END:variables


    public JComboBox<String> getComputingDocTypeCombo() {
        return computingDocTypeCombo;
    }
}
