/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.corneliu.forms.UI;

import com.corneliu.forms.service.DocumentProcessor;
import com.corneliu.forms.service.DocumentType;
import com.corneliu.forms.service.impl.DocumentProcessorImpl;

import javax.swing.*;
import java.io.IOException;
import java.util.List;

/**
 *
 * @author corneliu
 */
public class SimpleDocumentTypePanel extends javax.swing.JPanel {

    private MainFrame2 mainFrame;
    private DocumentProcessor documentProcessor;

    /**
     * Creates new form ComputingDocumentTypePanel
     */
    public SimpleDocumentTypePanel(MainFrame2 mainFrame) {
        this.mainFrame = mainFrame;
        this.documentProcessor = new DocumentProcessorImpl();

        initComponents();

        simpleDocTypeCombo.setModel(new DefaultComboBoxModel<>());

        List<String> allCustomDictionaries = documentProcessor.getAllCustomDictionaries();
        for (String file : allCustomDictionaries) {
            ((DefaultComboBoxModel) simpleDocTypeCombo.getModel()).addElement(file);
        }

        simpleDocTypeCombo.addActionListener(e -> this.mainFrame.reloadDictionary());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        simpleDocTypeCombo = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();

        jButton1.setText("Adauga Document Nou");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(simpleDocTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(235, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpleDocTypeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String name = JOptionPane.showInputDialog("Numele noului document");
        DocumentType.SIMPLE.setName(name.toUpperCase().replace(" ", "_"));

        try {
            documentProcessor.createDictionary(DocumentType.SIMPLE);
            ((DefaultComboBoxModel)simpleDocTypeCombo.getModel()).addElement(name);
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Nu a reusit adaugarea unui document nou: " + e.getMessage());
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> simpleDocTypeCombo;
    // End of variables declaration//GEN-END:variables


    public JComboBox<String> getSimpleDocTypeCombo() {
        return simpleDocTypeCombo;
    }
}
